### ISSUE TITLE
contrib.sites incompatibility?

### ISSUE THREAD

**Issue by julian998-dot** [megalus/django-google-sso#33]
Hi,

I been using django-google-sso in my project for a small site and a help desk,  before add the help desk the SSO works perfect!
But for the correct use of the models in the HelpDesk i need to use :

`
INSTALLED_APPS= [
....
    'django.contrib.sites',  
....
]
`

App that generate these on the library at the moment of making the callback with Google:

`
redirect_uri=http://example.com/google_sso/callback/
`

Making an error in the Google Console.
It's not taking the http://localhost:8000/, http://127.0.0.1:8000/ or the URL of the site.
I really dont know how to go around this issue.

I really appreciate that someone can help me with this!

**Comment by chrismaille** [comment]
Hi @julian998-dot ,

Thanks for the contact. The `example.com` domain is created when django starts the Django Sites Framework. For the callback, Django-Google-SSO will look, at this order:

1. The value from GOOGLE_SSO_CALLBACK_DOMAIN
2. The value from `get_current_site` as per [Django Sites Framework](https://docs.djangoproject.com/en/5.0/ref/contrib/sites/#getting-the-current-domain-for-display)

Probably the helpdesk package you mentioned starts the Django Sites Framework in your Project. That's why you have the default site (example.com) generated in your database.

You can try use the option `GOOGLE_SSO_CALLBACK_DOMAIN` to manually set the redirect URL:

```python
# settings.py

GOOGLE_SSO_CALLBACK_DOMAIN="localhost:8000" # or env.MY_SSO_DOMAIN or something similar using dotenv files
```

But this can resolve only your local development. I suggest you read the helpdesk package on why it uses the Django Sites Framework, to correct config this option, if need it.

**Comment by umerghayaz** [comment]
how can i insert google sign in icon in html ?

**Comment by chrismaille** [comment]
Hi, @umerghayaz ,
Thanks for the contact. If you need to change the icon shown on the button, you can use the `GOOGLE_SSO_LOGO_URL` option:

```python
# settings.py

GOOGLE_SSO_LOGO_URL="https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/512px-Google_%22G%22_Logo.svg.png"  # default value
```
